---
- name: install ferm
  apt: pkg=ferm
  tags:
   - ferm
   - packages

- name: create dirs
  file: path="/etc/ferm/{{ item }}" state=directory mode=750 owner=root group=root
  with_items:
   - defs
   - input
   - forward
   - output
   - raw_prerouting
  tags:
   - ferm
   - config

- name: create dirs (ipv6)
  file: path="/etc/ferm/{{ item }}" state=directory mode=750 owner=root group=root
  with_items:
   - input6
   - forward6
   - output6
   - raw_prerouting6
  when: ferm_ipv6
  tags:
   - ferm
   - config

- name: ferm.conf
  template: src=ferm.conf dest=/etc/ferm/ferm.conf
  notify:
    - restart ferm
  tags:
    - ferm
    - config
