---

- name: Set worker var
  set_fact:
    worker: "{{ worker_type }}-{{ worker_index|default('0') }}"

- name: Put {{ worker }} config in place
  template:
    src: "worker.yaml"
    dest: "/etc/matrix-synapse/workers/{{ worker }}.yaml"
    mode: '644'
  notify: config worker services

- name: Put {{ worker }} logging config in place
  template:
    src: "log.yaml"
    dest: "/etc/matrix-synapse/worker-logs/{{ worker }}-log.yaml"
    mode: '644'
  notify: config worker services

- name: Add {{ worker }} to synapse_worker_services
  set_fact:
    synapse_worker_services: "{{ synapse_worker_services + [ worker ] }}"
