---

depends:
  - lsb-release
  - wget
  - apt-transport-https
  - python3-pysaml2
  - python3-psycopg2
  - acl

synapse_psql_host: localhost
synapse_psql_user: "{{ psql_dbs['matrix-synapse']['user'] }}"
synapse_psql_pw: "{{ psql_dbs['matrix-synapse']['password'] }}"
synapse_psql_db: "{{ synapse_psql_user }}"

matrix_max_upload_size_mb: 100
synapse_metrics: no
synapse_presence: yes

synchrotron_workers:
  balancer: generic_sync
  init: generic_init_sync

persister_workers:
  - event_persister
  - typing_persister
  - account_persister
  - device_persister
  - presence_persister
  - receipt_persister
